apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: jobs.daemonset.darkowlzz.space
spec:
  group: daemonset.darkowlzz.space
  names:
    kind: Job
    plural: jobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            args:
              items:
                type: string
              type: array
            image:
              type: string
            mountPath:
              type: string
          required:
          - image
          - args
          - mountPath
          type: object
        status:
          properties:
            completed:
              type: string
            phase:
              type: string
          required:
          - completed
          - phase
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
