# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/darkowlzz/daemonset-job
    environment:
      version: 1.0.1
      arch: amd64
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get golang.org/x/lint/golint
      - run: curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz
      - run: tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
      - run: sudo mv kubebuilder_${version}_linux_${arch} /usr/local/kubebuilder
      - run: make all
