apiVersion: daemonset.darkowlzz.space/v1beta1
kind: Job
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: job-sample
spec:
  image: darkowlzz/cleanup:v0.0.2
  args: ["/basetarget/foo"]
  mountPath: "/tmp"
